# https://ci.appveyor.com/project/olegsych/monitor/settings/yaml

version: "{build}"

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_tags: true

image: Visual Studio 2022

clone_script:
- cmd: git clone --recurse-submodules -c core.symlinks=true https://github.com/%APPVEYOR_REPO_NAME%.git .\
- ps: >-
    if($env:APPVEYOR_PULL_REQUEST_NUMBER) {
        git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
        git checkout --recurse-submodules -qf FETCH_HEAD
    } else {
        git checkout --recurse-submodules -qf $env:APPVEYOR_REPO_COMMIT
    }

build_script:
- cmd: dotnet build .\Athene.sln -logger:"C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll"

test_script:
- cmd: dotnet test .\Athene.sln

after_test:
- cmd: dotnet pack .\Athene.sln --configuration Release --include-symbols

artifacts:
- path: bin\release\*.*nupkg
